image: node:latest

stages:
  - build
  - release

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

restart_pm2:
  stage: release
  script:
    - npm install pm2 -g
    - pm2 start ~/todos-app-api/server.js
    - pm2 startup ubuntu
